# Generated by Django 4.2.20 on 2025-03-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Укажите время приготовления (не менее 1 минуты)', verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Добавьте фото готового блюда', upload_to='recipes/images/', verbose_name='Изображение блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Добавьте ингредиенты и их количество', through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='Ингредиенты рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Укажите название рецепта', max_length=256, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Укажите тег', to='recipes.tag', verbose_name='Тег рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Добавьте описание рецепта', verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Укажите слаг', max_length=32, unique=True, verbose_name='Слаг'),
        ),
    ]
