# Generated by Django 4.2.20 on 2025-03-19 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Укажите единицу измерения', max_length=256, validators=[django.core.validators.MaxLengthValidator], verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите ингредиент', max_length=256, validators=[django.core.validators.MaxLengthValidator], verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Укажите время приготовления (не менее 1 минуты)', validators=[django.core.validators.MaxLengthValidator(43800), django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Укажите название рецепта', max_length=256, validators=[django.core.validators.MaxLengthValidator], verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Укажите количество', validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиента в рецепте'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Укажите название тега', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator], verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Укажите слаг', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator], verbose_name='Слаг'),
        ),
    ]
