# Generated by Django 4.2.20 on 2025-03-28 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Укажите единицу измерения', max_length=64, validators=[django.core.validators.MaxLengthValidator], verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите ингредиент', max_length=128, validators=[django.core.validators.MaxLengthValidator], verbose_name='Ингредиент'),
        ),
    ]
