# Generated by Django 4.2.20 on 2025-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipeingredient_unique_recipe_ingredient_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
