# Generated by Django 4.2.20 on 2025-04-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_short_link'),
        ('recipes', '0007_recipe_short_url'),
    ]

    operations = [
    ]
