# Generated by Django 4.2.20 on 2025-04-07 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_merge_0007_recipe_short_link_0007_recipe_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Укажите количество', validators=[django.core.validators.MaxValueValidator(10000, 'Количество ингредиента превышает 10000')], verbose_name='Количество ингредиента в рецепте'),
        ),
    ]
