# Generated by Django 4.2.20 on 2025-04-07 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_short_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Укажите количество', validators=[django.core.validators.MaxValueValidator(10000, 'Количество ингредиента превышает 10000'), django.core.validators.MinValueValidator(1, 'Значение времени приготовления меньше 1')], verbose_name='Количество ингредиента в рецепте'),
        ),
    ]
