# Generated by Django 4.2.20 on 2025-04-07 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Укажите время приготовления (не менее 1 минуты)', validators=[django.core.validators.MaxValueValidator(43800, 'Значение времени приготовления превышает 43800')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Укажите количество', verbose_name='Количество ингредиента в рецепте'),
        ),
    ]
