# Generated by Django 4.2.20 on 2025-04-07 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Укажите время приготовления (не менее 1 минуты)', validators=[django.core.validators.MaxValueValidator(43800, 'Значение времени приготовления превышает 43800'), django.core.validators.MinValueValidator(1, 'Значение времени приготовления меньше 1')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Укажите количество', validators=[django.core.validators.MaxValueValidator(10000, 'Количество ингредиента превышает 10000'), django.core.validators.MinValueValidator(1, 'Значение времени приготовления меньше 1')], verbose_name='Количество ингредиента в рецепте'),
        ),
    ]
