# Generated by Django 4.2.20 on 2025-03-19 11:12

import django.core.validators
from django.db import migrations, models

# import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Укажите e-mail', max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator,], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Укажите логин пользователя', max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator,], verbose_name='Логин'),
        ),
    ]
