# Generated by Django 4.2.20 on 2025-04-03 12:44

import django.contrib.auth.validators
from django.db import migrations, models
# import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Укажите e-mail', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Укажите имя', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Укажите фамилию', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Укажите логин пользователя', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(),], verbose_name='Логин'),
        ),
    ]
