# Generated by Django 4.2.20 on 2025-04-03 14:00

from django.db import migrations, models
# import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Укажите e-mail. E-mail не должен превышать 254 символов.', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
