# Generated by Django 4.2.20 on 2025-04-03 14:04

from django.db import migrations, models
# import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Укажите логин пользователя. Используйте буквы, цифры и символы @/./+/-/_. Логин не может начинаться цифрой и превышать 150 символов.', max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
