# Generated by Django 4.2.20 on 2025-04-03 14:07

import django.contrib.auth.validators
from django.db import migrations, models
# import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Укажите логин пользователя. Используйте буквы, цифры и символы @/./+/-/_. Логин не может начинаться цифрой и превышать 150 символов.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(),], verbose_name='Логин'),
        ),
    ]
